### ISSUE TITLE
possible PMIx server race: PMIx_server_register_client vs fence

### ISSUE THREAD

**Issue by garlick** [pmix/master#89] opened 2016-05-12 21:34 UTC
As noted in #60, if a client enters a fence before all the clients on the same node have been registered with `PMIx_server_register_client()`, the fence will not complete.  This log snippet demonstrates the problem in a 16-node test.  Note rank 12 registers after one of the ranks calls fence.  This is because process launching and registration are done in parallel in the test server:
```
[jimbo:59144] recvd FENCE
[jimbo:59144] recvd fence with 1 procs
[jimbo:59144] get_tracker called with 1 procs
[jimbo:59144] new_tracker called with 1 procs
[jimbo:59144] get_tracker called with 1 procs
[jimbo:59144] adding new tracker with 1 procs
[jimbo:59144] new_tracker: all clients not registered nspace FLUX-START
snip
[jimbo:59144] pmix:server setup_fork for nspace FLUX-START rank 12
[jimbo:59144] pmix:server register client FLUX-START:12
[jimbo:59144] pmix:server _register_client for nspace FLUX-START rank 12
```

This can also be demonstrated with `pmix_test`.  I find the following hangs pretty reliably for me
```
./pmix_test -n 256 -e ./pmix_client
```
while with the patch below, I can run up to around `-n 800`, when I run out of file descriptors
```diff
diff --git a/test/utils.c b/test/utils.c
index 87c7e6a..b3fad58 100644
--- a/test/utils.c
+++ b/test/utils.c
@@ -183,16 +183,21 @@ int launch_clients(int num_procs, char *binary, char *** client_env, char ***bas
     myuid = getuid();
     mygid = getgid();
 
-    /* fork/exec the test */
+    /* register clients */
     for (n = 0; n < num_procs; n++) {
-        proc.rank = counter;
-        if (PMIX_SUCCESS != (rc = PMIx_server_setup_fork(&proc, client_env))) {//n
+        proc.rank = n;
+        if (PMIX_SUCCESS != (rc = PMIx_server_register_client(&proc, myuid, mygid, NULL, NULL, NULL))) {//n
             TEST_ERROR(("Server fork setup failed with error %d", rc));
             PMIx_server_finalize();
             cli_kill_all();
             return rc;
         }
-        if (PMIX_SUCCESS != (rc = PMIx_server_register_client(&proc, myuid, mygid, NULL, NULL, NULL))) {//n
+    }
+
+    /* fork/exec the test */
+    for (n = 0; n < num_procs; n++) {
+        proc.rank = counter;
+        if (PMIX_SUCCESS != (rc = PMIx_server_setup_fork(&proc, client_env))) {//n
             TEST_ERROR(("Server fork setup failed with error %d", rc));
             PMIx_server_finalize();
             cli_kill_all();
```

If it's required for all `PMIx_server_register_client()` calls to complete before processes are launched, this should be documented and the tests fixed as above.  o/w maybe it's a race that should be addressed elsewhere?

**Comment by annu13** [comment] 2016-05-12 22:38
@garlick The PMIx server is setup to handle this race condition, but I guess there is a minor bug in that code. Could you try this and see - set trk->def_complete = true in pmix_server.c at line 773 after the check. 
 PMIX_LIST_FOREACH(trk, &pmix_server_globals.collectives, pmix_server_trkr_t) {
            /* if this tracker is already complete, then we
             * don't need to update it */
            if (trk->def_complete) {
                continue;
            }
            /* is this now completed? */
            if (pmix_list_get_size(&trk->local_cbs) == trk->nlocal) {

**Comment by garlick** [comment] 2016-05-12 22:55
LIke this?  Doesn't seem to help...

```diff
diff --git a/src/server/pmix_server.c b/src/server/pmix_server.c
index d74ed4d..470260a 100644
--- a/src/server/pmix_server.c
+++ b/src/server/pmix_server.c
@@ -770,6 +770,7 @@ static void _register_client(int sd, short args, void *cbdata)
             if (trk->def_complete) {
                 continue;
             }
+           trk->def_complete = true; // XXX
             /* is this now completed? */
             if (pmix_list_get_size(&trk->local_cbs) == trk->nlocal) {
                 /* it did, so now we need to process it
```

**Comment by rhc54** [comment] 2016-05-12 23:15
I'll poke at this later - the nspace must of course be registered first, but you should be able to register_client on the fly.

**Comment by annu13** [comment] 2016-05-12 23:17
hmmm...looks like there are more bugs in that code, I will try to reproduce it on my system and see whats going on.

**Comment by rhc54** [comment] 2016-05-12 23:21
I don't think you meant to close this... 😄

**Comment by annu13** [comment] 2016-05-12 23:23
oops!! sorry, I selected the wrong button.

**Comment by annu13** [comment] 2016-05-17 09:02
I was able to reproduce the issue on my system. The two checks based on which the PMIx server decides if all local participants have called fence are not getting set corrected when Fence is called by any processes before all clients are registered.
 if (trk->def_complete &&
        pmix_list_get_size(&trk->local_cbs) == trk->nlocal)
once all clients are registered the track needs to be update with the newly added clients (update trk->nlocal) and it should be marked as def_complete. It worked with the fixes that I put to address this. I will push the changes shortly.

**Comment by annu13** [comment] 2016-05-17 09:06
This issue prompts a question about how a hanging fence is handled in the event of a process failure - do we need a timeout mechanism, or a way to release the fence?

**Comment by garlick** [comment] 2016-05-17 13:43
> It worked with the fixes that I put to address this. I will push the changes shortly.

Nice @annu13 - happy to cherry pick your commit(s) and try it on my setup once you've got something pushed.

**Closed** 2016-05-24 03:54 UTC
